# Site settings
# ----------------------------------------------------------------
locale: "en-GB"
title: Computer Science
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

email: sahumphreys@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Just a dummy site for now testing functionality of GH pages and Jekyll
baseurl: "" # "/sahumphreys.github.io" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

# -- Site Author
author:
  name: Simon Humphreys
  initials: SAH
  bio: "Useful to put something about me here"
  email: sahumphreys@protonmail.com 
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto: sahumphreys@protonmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sahumphreys"

# -- Build settings
theme: null
plugins:
  - jekyll-feed

include: ['_pages']

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default
  - 
    scope:
      path: ""
      type: gcse
    values:
      layout: page
      is_post: false
      toc: true

# -- COLLECTIONS
collections:
  gcse:
    output: true
    permalink: /:collection/:path
  # alevel:
  #   output: true
  #   permalink: /alevel/:path

# -- MARKDOWN --
#markdown: kramdown

kramdown:
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  highlighter: rouge
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: true
  # syntax_highlighter: rouge


  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
